### ISSUE TITLE
Feature request: Do I have enough for pity?

### ISSUE THREAD

**Issue by Sahasrahla** [genshin-wishes/genshin-wishes-ui#1]
I would like a field where I can enter my current inventory of Acquaint / Intertwined Fates as well as my current Primogems. You can then use that info to determine how far away I am from reaching my next 5* Pity on each banner. For example: I currently have 0/90 on the Event Banner (I stopped wishing as soon as I pulled Ganyu). I have now saved up 22 Intertwined Fates and 10,879 Primos. Quick math tells me that's ~89 wishes, but it'd be neat if your site could do that quick math for me.

For extra bonus points, you could also have calculations for the potential Primogems/Fates available between now and the end of the current Event Banner:
60/day from Daily Commissions
90/day from Blessing of the Welkin Moon
5/mo from Masterless Stardust
420 from the current Vishap event
I don't know how easy it is to calculate / estimate Masterless Starglitter, but those too?

Obviously you can't predict every Primogem that will be available for us. There are Achievements, Developer Update videos with redeem codes, web events and other variables you wouldn't be able to account for obviously, but it would still be a great indicator of roughly how close we can get to bringing home the current Banner character before they're gone.

I tracked this info manually in an Excel sheet during the Ganyu banner, and found I was going to fall about 1800 Primos short of guaranteed Pity. I ended up using that knowledge to purchase a pack of gems to bridge the gap.

**Comment by jvergerolle** [comment]
Hi, thanks for sharing your ideas. I had the same calculator idea when we started the project and that is something we would love to add to the site. However we have some more important features to release right now, so it will not be online any time soon.

About your other idea, although it looks very useful it will be difficult to maintain for us. There is of course a basic income of primogems that we can use (but it will be different for cash players and f2p players). And the main issue here is finding and updating new primogems sources on every event, it will be too much time consuming.
