### ISSUE TITLE
Title localization issue

### ISSUE THREAD

**Issue by tzm41** [genshin-wishes/genshin-wishes-ui#2]
<img width="307" alt="Screen Shot 2021-03-05 at 6 25 18 PM" src="https://user-images.githubusercontent.com/5728283/110191941-28778580-7de0-11eb-90e3-c5b72cd1c668.png">

English localization missing the "wishes" word in the title.

**Comment by Ishou** [comment]
Oopsie! Thanks for the heads up, it'll be fixed next release.

**Comment by tzm41** [comment]
Looks fixed, thank you!
